Update 8.deploy-to-server.yml

diff --git a/.github/workflows/8.deploy-to-server.yml b/.github/workflows/8.deploy-to-server.yml
--- a/.github/workflows/8.deploy-to-server.yml
+++ b/.github/workflows/8.deploy-to-server.yml
@@ -42,7 +42,26 @@ jobs:
           username: ${{ secrets.EC2_SSH_USER }}
           key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
           script: |
-           echo "starting deploymet"
+           echo "Starting deployment..."
+           if ! command -v docker &> /dev/null
+           then
+            echo "Docker not found. Installing Docker..."
+            sudo apt update
+            sudo apt install docker.io -y
+            sudo systemctl start docker
+            sudo systemctl enable docker
+            sudo usermod -aG docker $USER
+           else
+            echo "Docker already installed"
+           fi
+           
+           if ! docker compose version &> /dev/null
+           then
+            echo "Docker Compose not found. Installing Docker Compose..."
+            sudo apt install docker-compose-v2 -y
+           else
+            echo "Docker Compose already installed"
+           fi
            export DOCKERHUB_USER=${{ vars.DOCKERHUB_USER }}
            export DOCKER_TAG=${{ github.sha }}
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
